[project]
name = "python_2025_11"
version = "0.1.0"
description = "test project"
readme = "readme.md"
requires-python = ">=3.12"
dependencies = [
    "sqlalchemy==2.0.39",
    "pytest",
]
[dependency-groups]
dev = [
  "pylint==3.3.5",
  "pytest==8.3.5",
]
[tool.pylint.main]
ignore-paths = ".venv"